export * from './circle.js'
export * from './triangle.js'
export * from './polygon.js'
export * from './shape2.js'
export * from './rectangle.js'
export * from './line.js'
export * from './capsule.js'
